services:
  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile
    container_name: virelai-api
    ports:
      - "8000:8000"
    volumes:
      - ./services/api:/app
    environment:
      DATABASE_URL: postgresql+psycopg://virelai:virelai@postgres:5432/virelai
      REDIS_URL: redis://redis:6379/0
      KAFKA_BOOTSTRAP_SERVERS: kafka:19092
      S3_ENDPOINT_URL: http://minio:9000
      S3_PUBLIC_ENDPOINT_URL: http://localhost:9000

      S3_ACCESS_KEY: virelai
      S3_SECRET_KEY: virelai-dev-password
      S3_REGION: us-east-1

      S3_BUCKET_ORIGINALS: virelai-originals
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
      minio:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:17-alpine
    container_name: virelai-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: virelai
      POSTGRES_PASSWORD: virelai
      POSTGRES_DB: virelai
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U virelai -d virelai"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: virelai-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  kafka:
    image: apache/kafka:4.3.1
    container_name: virelai-kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      # Single-node KRaft configuration
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # Internal Docker traffic uses kafka:19092.
      # Programs running directly on Windows use localhost:9092.
      KAFKA_LISTENERS: CONTROLLER://:9093,PLAINTEXT://:19092,PLAINTEXT_HOST://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:19092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      # Required for a one-broker local cluster
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_SHARE_COORDINATOR_STATE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_SHARE_COORDINATOR_STATE_TOPIC_MIN_ISR: 1

      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs

      CLUSTER_ID: 4L6g3nShT-eMCtK--X86sw



    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list > /dev/null 2>&1"
        ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 20s

    restart: unless-stopped

  minio:
    image: quay.io/minio/minio:latest
    container_name: virelai-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: virelai
      MINIO_ROOT_PASSWORD: virelai-dev-password
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:9000/minio/health/live || exit 1"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  minio-init:
    image: minio/mc:latest
    container_name: virelai-minio-init
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      mc alias set local http://minio:9000 virelai virelai-dev-password &&
      mc mb --ignore-existing local/virelai-originals &&
      mc mb --ignore-existing local/virelai-media &&
      mc anonymous set download local/virelai-media &&
      exit 0;
      "


  transcoder:
    build:
      context: ./services/transcoder
      dockerfile: Dockerfile

    container_name: virelai-transcoder

    environment:
      DATABASE_URL: postgresql://virelai:virelai@postgres:5432/virelai

      KAFKA_BOOTSTRAP_SERVERS: kafka:19092
      KAFKA_TOPIC_VIDEO_UPLOADED: video.uploaded.v1

      S3_ENDPOINT_URL: http://minio:9000
      S3_ACCESS_KEY: virelai
      S3_SECRET_KEY: virelai-dev-password
      S3_REGION: us-east-1

      S3_BUCKET_ORIGINALS: virelai-originals
      S3_BUCKET_MEDIA: virelai-media

    volumes:
      - ./services/transcoder/app:/app/app

    depends_on:
      postgres:
        condition: service_healthy

      kafka:
        condition: service_healthy

      minio:
        condition: service_healthy

    restart: unless-stopped


volumes:
  postgres_data:
  redis_data:
  minio_data: