"""add uploads

Revision ID: 0bdf27d2aa0a
Revises: 299d0e8453a6
Create Date: 2026-09-10 20:57:16.847384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bdf27d2aa0a'
down_revision: Union[str, Sequence[str], None] = '299d0e8453a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('object_key', sa.String(length=1024), nullable=False),
    sa.Column('multipart_upload_id', sa.String(length=1024), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=127), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('part_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('part_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('initiated', 'completed', 'aborted', 'failed', name='upload_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_uploads_video_status', 'uploads', ['video_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_uploads_video_status', table_name='uploads')
    op.drop_table('uploads')
    # ### end Alembic commands ###
