"""add playback qoe telemetry

Revision ID: 39c678287d68
Revises: 81d08df8549e
Create Date: 2026-09-11 00:29:49.611402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39c678287d68'
down_revision: Union[str, Sequence[str], None] = '81d08df8549e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playback_events', sa.Column('startup_time_ms', sa.BigInteger(), nullable=True))
    op.add_column('playback_events', sa.Column('watch_delta_ms', sa.BigInteger(), nullable=True))
    op.add_column('playback_events', sa.Column('seek_from_ms', sa.BigInteger(), nullable=True))
    op.add_column('playback_events', sa.Column('seek_to_ms', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playback_events', 'seek_to_ms')
    op.drop_column('playback_events', 'seek_from_ms')
    op.drop_column('playback_events', 'watch_delta_ms')
    op.drop_column('playback_events', 'startup_time_ms')
    # ### end Alembic commands ###
