"""add playback sessions and events

Revision ID: 81d08df8549e
Revises: 510b22718081
Create Date: 2026-09-10 23:18:14.468260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81d08df8549e'
down_revision: Union[str, Sequence[str], None] = '510b22718081'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playback_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_playback_sessions_video_started', 'playback_sessions', ['video_id', 'started_at'], unique=False)
    op.create_table('playback_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('playback_position_ms', sa.BigInteger(), nullable=True),
    sa.Column('buffer_duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('bitrate_kbps', sa.Integer(), nullable=True),
    sa.Column('quality_height', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=128), nullable=True),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['playback_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'sequence_number', name='uq_playback_event_session_sequence')
    )
    op.create_index('ix_playback_events_type_time', 'playback_events', ['event_type', 'event_time'], unique=False)
    op.create_index('ix_playback_events_video_time', 'playback_events', ['video_id', 'event_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_playback_events_video_time', table_name='playback_events')
    op.drop_index('ix_playback_events_type_time', table_name='playback_events')
    op.drop_table('playback_events')
    op.drop_index('ix_playback_sessions_video_started', table_name='playback_sessions')
    op.drop_table('playback_sessions')
    # ### end Alembic commands ###
