"""add video media metadata and renditions

Revision ID: 9718244ca9dd
Revises: 0bdf27d2aa0a
Create Date: 2026-09-10 21:37:25.428305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9718244ca9dd'
down_revision: Union[str, Sequence[str], None] = '0bdf27d2aa0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('renditions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('video_bitrate_kbps', sa.Integer(), nullable=False),
    sa.Column('audio_bitrate_kbps', sa.Integer(), nullable=True),
    sa.Column('video_codec', sa.String(length=64), nullable=False),
    sa.Column('audio_codec', sa.String(length=64), nullable=True),
    sa.Column('playlist_key', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id', 'height', name='uq_renditions_video_height')
    )
    op.create_index('ix_renditions_video_id', 'renditions', ['video_id'], unique=False)
    op.add_column('videos', sa.Column('duration_ms', sa.BigInteger(), nullable=True))
    op.add_column('videos', sa.Column('source_width', sa.Integer(), nullable=True))
    op.add_column('videos', sa.Column('source_height', sa.Integer(), nullable=True))
    op.add_column('videos', sa.Column('source_codec', sa.String(length=64), nullable=True))
    op.add_column('videos', sa.Column('thumbnail_key', sa.String(length=1024), nullable=True))
    op.add_column('videos', sa.Column('master_playlist_key', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'master_playlist_key')
    op.drop_column('videos', 'thumbnail_key')
    op.drop_column('videos', 'source_codec')
    op.drop_column('videos', 'source_height')
    op.drop_column('videos', 'source_width')
    op.drop_column('videos', 'duration_ms')
    op.drop_index('ix_renditions_video_id', table_name='renditions')
    op.drop_table('renditions')
    # ### end Alembic commands ###
